# Setup
title:      Notes and Musings by Soumya Veer
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Soumya Veer
  url:        https://soumya.site

collections:
  technology_blog:
    output: true
    permalink: /technology/posts/:name

  book_blog:
    output: true
    permalink: /personal/books/:name

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
