# Setup
title:      Notes and Musings by Soumya Veer
baseurl:      ""
paginate:     5

# About/contact
author:
  name:       Soumya Veer
  url:        https://soumya.site

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
