title:      Notes and Musings by Soumya Veer
baseurl:      ""
paginate:     5

author:
  name:       Soumya Veer
  url:        https://www.soumyathinks.com

collections:
  technology_blog:
    output: true
    permalink: /technology/blog/:name

  book_blog:
    output: true
    permalink: /personal/books/:name

gems:
  - jekyll-paginate
  - jekyll-redirect-from

include: ["_pages"]

# Configure addons
markdown: kramdown
