title:      Notes and Musings by Soumya Veer
baseurl:      ""

author:
  name:       Soumya Veer
  url:        https://www.soumyathinks.com

collections:
  technology_blog:
    output: true
    permalink: /technology/blog/:name

  book_blog:
    output: true
    permalink: /personal/books/:name

include: ["_pages"]

# Configure addons
markdown: kramdown

plugins:
  - jekyll-redirect-from
